SET SESSION FOREIGN_KEY_CHECKS=0;

/* Drop Tables */

DROP TABLE IF EXISTS BOARD_COMMENT;
DROP TABLE IF EXISTS BOARD_IMG_FILE;
DROP TABLE IF EXISTS BOARD_LIKE;
DROP TABLE IF EXISTS BOARD_INFO;
DROP TABLE IF EXISTS MOUNTAIN_COMMENT;
DROP TABLE IF EXISTS MOUNTAIN_USER_LIKE;
DROP TABLE IF EXISTS PARTY_BOARD_COMMENT;
DROP TABLE IF EXISTS PARTY_BOARD_LIKE;
DROP TABLE IF EXISTS PARTY_BOARD;
DROP TABLE IF EXISTS PARTY_MEMBER;
DROP TABLE IF EXISTS PARTY_USER_LIKE;
DROP TABLE IF EXISTS PARTY_INFO;
DROP TABLE IF EXISTS MOUNTAIN_INFO;
DROP TABLE IF EXISTS USER_CHALLENGE;
DROP TABLE IF EXISTS USER_INFO;




/* Create Tables */

CREATE TABLE BOARD_COMMENT
(
	BC_NUM int NOT NULL AUTO_INCREMENT,
	BI_NUM int NOT NULL,
	UI_NUM int NOT NULL,
	BC_COMMENT varchar(300) NOT NULL,
	BC_ACTIVE int(1) NOT NULL,
	BC_CREDAT char(8) DEFAULT 'DATE_FORMAT(NOW(), ''%Y%m%d'')' NOT NULL,
	BC_LMODAT char(8) DEFAULT 'DATE_FORMAT(NOW(), ''%Y%m%d'')' NOT NULL,
	PRIMARY KEY (BC_NUM)
);


CREATE TABLE BOARD_IMG_FILE
(
	BIF_NUM int NOT NULL AUTO_INCREMENT,
	BI_NUM int NOT NULL,
	BIF_IMG_PATH varchar(300) NOT NULL,
	PRIMARY KEY (BIF_NUM)
);


CREATE TABLE BOARD_INFO
(
	BI_NUM int NOT NULL AUTO_INCREMENT,
	UI_NUM int NOT NULL,
	BI_CATEGORY varchar(20) NOT NULL,
	BI_TITLE varchar(30) NOT NULL,
	BI_CONTENT text NOT NULL,
	BI_CNT int NOT NULL,
	BI_CREDAT char(8) DEFAULT 'DATE_FORMAT(NOW(), ''%Y%m%d'')' NOT NULL,
	BI_CRETIM char(6) DEFAULT 'DATE_FORMAT(NOW(), ''%H%i%s'')' NOT NULL,
	BI_LMODAT char(8) DEFAULT 'DATE_FORMAT(NOW(), ''%Y%m%d'')' NOT NULL,
	BI_LMOTIM char(6) DEFAULT 'DATE_FORMAT(NOW(), ''%H%i%s'')' NOT NULL,
	BI_ACTIVE int(1) NOT NULL,
	PRIMARY KEY (BI_NUM)
);


CREATE TABLE BOARD_LIKE
(
	BL_NUM int NOT NULL AUTO_INCREMENT,
	BI_NUM int NOT NULL,
	UI_NUM int NOT NULL,
	PRIMARY KEY (BL_NUM)
);


CREATE TABLE MOUNTAIN_COMMENT
(
	MC_NUM int NOT NULL AUTO_INCREMENT,
	MI_NUM int NOT NULL,
	UI_NUM int NOT NULL,
	MC_COMMENT varchar(300) NOT NULL,
	MC_ACTIVE int(1) NOT NULL,
	MC_CREDAT char(8) DEFAULT 'DATE_FORMAT(NOW(), ''%Y%m%d'')',
	MC_LMODAT char(8) DEFAULT 'DATE_FORMAT(NOW(), ''%Y%m%d'')',
	PRIMARY KEY (MC_NUM)
);


CREATE TABLE MOUNTAIN_INFO
(
	MI_NUM int NOT NULL AUTO_INCREMENT,
	MNTNCD char(9) NOT NULL,
	MNTNM char(15) NOT NULL,
	MNTHEIGHT int(5) NOT NULL,
	AREANM varchar(300) NOT NULL,
	AEATREASON text NOT NULL,
	ETCCOURSE text NOT NULL,
	OVERVIEW text NOT NULL,
	MI_CREDAT char(8) NOT NULL,
	MI_LMODAT char(8),
	SUBUM varchar(300) NOT NULL,
	TOURISMINF text,
	DETAILS text,
	MI_IMG_URL varchar(500),
	LAT float NOT NULL,
	LOT float NOT NULL,
	PRIMARY KEY (MI_NUM),
	UNIQUE (MNTNCD),
	UNIQUE (MNTNM)
);


CREATE TABLE MOUNTAIN_USER_LIKE
(
	MUL_NUM int NOT NULL AUTO_INCREMENT,
	MI_NUM int NOT NULL,
	UI_NUM int NOT NULL,
	MUL_CREDAT char(8),
	PRIMARY KEY (MUL_NUM)
);


CREATE TABLE PARTY_BOARD
(
	PB_NUM int NOT NULL AUTO_INCREMENT,
	PI_NUM int NOT NULL,
	UI_NUM int NOT NULL,
	PB_CONTENT text NOT NULL,
	PB_CREDAT char(8) DEFAULT 'DATE_FORMAT(NOW(), ''%Y%m%d'')' NOT NULL,
	PB_CRETIM char(6) DEFAULT 'DATE_FORMAT(NOW(), ''%H%i%s'')' NOT NULL,
	PB_LMODAT char(8) DEFAULT 'DATE_FORMAT(NOW(), ''%Y%m%d'')' NOT NULL,
	PB_LMOTIM char(6) DEFAULT 'DATE_FORMAT(NOW(), ''%H%i%s'')' NOT NULL,
	PB_ACTIVE int(1) NOT NULL,
	PRIMARY KEY (PB_NUM)
);


CREATE TABLE PARTY_BOARD_COMMENT
(
	PBC_NUM int NOT NULL AUTO_INCREMENT,
	PB_NUM int NOT NULL,
	UI_NUM int NOT NULL,
	PBC_COMMENT varchar(300) NOT NULL,
	PBC_CREDAT char(8) DEFAULT 'DATE_FORMAT(NOW(), ''%Y%m%d'')' NOT NULL,
	PBC_LMODAT char(8) DEFAULT 'DATE_FORMAT(NOW(), ''%Y%m%d'')' NOT NULL,
	PBC_ACTIVE int(1) NOT NULL,
	PBC_CRETIM char(8) DEFAULT 'DATE_FORMAT(NOW(), ''%H%i%s'')' NOT NULL,
	PBC_LMOTIM char(6) DEFAULT 'DATE_FORMAT(NOW(), ''%H%i%s'')' NOT NULL,
	PRIMARY KEY (PBC_NUM)
);


CREATE TABLE PARTY_BOARD_LIKE
(
	PBL_NUM int NOT NULL AUTO_INCREMENT,
	PB_NUM int NOT NULL,
	UI_NUM int NOT NULL,
	PBL_CREDAT char(8) DEFAULT 'DATE_FORMAT(NOW(), ''%Y%m%d'')' NOT NULL,
	PRIMARY KEY (PBL_NUM)
);


CREATE TABLE PARTY_INFO
(
	PI_NUM int NOT NULL AUTO_INCREMENT,
	MI_NUM int NOT NULL,
	UI_NUM int NOT NULL,
	PI_NAME varchar(50) NOT NULL,
	PI_EXPDAT char(8) NOT NULL,
	PI_MEETING_TIME char(6) NOT NULL,
	PI_MEMBER_CNT int(3) NOT NULL,
	PI_PROFILE varchar(2000),
	PI_CREDAT char(8) DEFAULT 'DATE_FORMAT(NOW(), ''%Y%m%d'')' NOT NULL,
	PI_LMODAT char(8) DEFAULT 'DATE_FORMAT(NOW(), ''%Y%m%d'')' NOT NULL,
	PI_ACTIVE int(1) NOT NULL,
	PRIMARY KEY (PI_NUM)
);


CREATE TABLE PARTY_MEMBER
(
	PM_NUM int NOT NULL AUTO_INCREMENT,
	PI_NUM int NOT NULL,
	UI_NUM int NOT NULL,
	PM_ACTIVE int(1) NOT NULL,
	PM_CREDAT char(8) DEFAULT 'DATE_FORMAT(NOW(), ''%Y%m%d'')' NOT NULL,
	PM_LMODAT char(8) DEFAULT 'DATE_FORMAT(NOW(), ''%Y%m%d'')' NOT NULL,
	PRIMARY KEY (PM_NUM)
);


CREATE TABLE PARTY_USER_LIKE
(
	PUL_NUM int NOT NULL AUTO_INCREMENT,
	PI_NUM int NOT NULL,
	UI_NUM int NOT NULL,
	PUL_CREDAT char(8) DEFAULT 'DATE_FORMAT(NOW(), ''%Y%m%d'')' NOT NULL,
	PRIMARY KEY (PUL_NUM)
);


CREATE TABLE USER_CHALLENGE
(
	UC_NUM int NOT NULL AUTO_INCREMENT,
	UI_NUM int NOT NULL,
	UC_CHALLENGE varchar(300) NOT NULL,
	UC_CREDAT char(8),
	UC_LMODAT char(8),
	PRIMARY KEY (UC_NUM)
);


CREATE TABLE USER_INFO
(
	UI_NUM int NOT NULL AUTO_INCREMENT,
	UI_ID varchar(30) NOT NULL,
	UI_PWD varchar(300) NOT NULL,
	UI_NAME varchar(20) NOT NULL,
	UI_NICKNAME char(10) NOT NULL,
	UI_ADDR varchar(300) NOT NULL,
	UI_ZONECODE char(5) NOT NULL,
	UI_AGE int(3) NOT NULL,
	UI_GENDER char(1) NOT NULL,
	UI_IMG_PATH varchar(400) NOT NULL,
	UI_CREDAT char(8) DEFAULT 'DATE_FORMAT(NOW(), ''%Y%m%d'')' NOT NULL,
	UI_ACTIVE int(1) NOT NULL,
	UI_GRADE int(1) NOT NULL,
	UI_LMODAT char(8) DEFAULT 'DATE_FORMAT(NOW(), ''%Y%m%d'')' NOT NULL,
	PRIMARY KEY (UI_NUM),
	UNIQUE (UI_ID)
);



/* Create Foreign Keys */

ALTER TABLE BOARD_COMMENT
	ADD FOREIGN KEY (BI_NUM)
	REFERENCES BOARD_INFO (BI_NUM)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE BOARD_IMG_FILE
	ADD FOREIGN KEY (BI_NUM)
	REFERENCES BOARD_INFO (BI_NUM)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE BOARD_LIKE
	ADD FOREIGN KEY (BI_NUM)
	REFERENCES BOARD_INFO (BI_NUM)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE MOUNTAIN_COMMENT
	ADD FOREIGN KEY (MI_NUM)
	REFERENCES MOUNTAIN_INFO (MI_NUM)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE MOUNTAIN_USER_LIKE
	ADD FOREIGN KEY (MI_NUM)
	REFERENCES MOUNTAIN_INFO (MI_NUM)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE PARTY_INFO
	ADD FOREIGN KEY (MI_NUM)
	REFERENCES MOUNTAIN_INFO (MI_NUM)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE PARTY_BOARD_COMMENT
	ADD FOREIGN KEY (PB_NUM)
	REFERENCES PARTY_BOARD (PB_NUM)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE PARTY_BOARD_LIKE
	ADD FOREIGN KEY (PB_NUM)
	REFERENCES PARTY_BOARD (PB_NUM)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE PARTY_BOARD
	ADD FOREIGN KEY (PI_NUM)
	REFERENCES PARTY_INFO (PI_NUM)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE PARTY_MEMBER
	ADD FOREIGN KEY (PI_NUM)
	REFERENCES PARTY_INFO (PI_NUM)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE PARTY_USER_LIKE
	ADD FOREIGN KEY (PI_NUM)
	REFERENCES PARTY_INFO (PI_NUM)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE BOARD_COMMENT
	ADD FOREIGN KEY (UI_NUM)
	REFERENCES USER_INFO (UI_NUM)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE BOARD_INFO
	ADD FOREIGN KEY (UI_NUM)
	REFERENCES USER_INFO (UI_NUM)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE BOARD_LIKE
	ADD FOREIGN KEY (UI_NUM)
	REFERENCES USER_INFO (UI_NUM)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE MOUNTAIN_COMMENT
	ADD FOREIGN KEY (UI_NUM)
	REFERENCES USER_INFO (UI_NUM)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE MOUNTAIN_USER_LIKE
	ADD FOREIGN KEY (UI_NUM)
	REFERENCES USER_INFO (UI_NUM)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE PARTY_BOARD
	ADD FOREIGN KEY (UI_NUM)
	REFERENCES USER_INFO (UI_NUM)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE PARTY_BOARD_COMMENT
	ADD FOREIGN KEY (UI_NUM)
	REFERENCES USER_INFO (UI_NUM)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE PARTY_BOARD_LIKE
	ADD FOREIGN KEY (UI_NUM)
	REFERENCES USER_INFO (UI_NUM)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE PARTY_INFO
	ADD FOREIGN KEY (UI_NUM)
	REFERENCES USER_INFO (UI_NUM)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE PARTY_MEMBER
	ADD FOREIGN KEY (UI_NUM)
	REFERENCES USER_INFO (UI_NUM)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE PARTY_USER_LIKE
	ADD FOREIGN KEY (UI_NUM)
	REFERENCES USER_INFO (UI_NUM)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE USER_CHALLENGE
	ADD FOREIGN KEY (UI_NUM)
	REFERENCES USER_INFO (UI_NUM)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;



